### ISSUE TITLE
Xcode 7 runtime error

### ISSUE THREAD

**Issue by shanksyang** [kasei/SwiftRegex#2]
struct RegexMatchCaptureGenerator : GeneratorType {
    var items: ArraySlice<String>
    mutating func next() -> String? {
        if items.isEmpty { return nil }
        let ret = items[0] //error, need to use items[items.startIndex]，because ArraySlice doesn't support 0 start index any more..
        items = items[1..<items.count]
        return ret
    }
}

**Comment by kasei** [comment]
Thanks for the report. Committing the fix now.
